
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: SmartParking
  latitude: 36.103295
  longitude: 129.387009
  elevation: 30
   
lovelace:
  mode: yaml
  #mode: storage

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

  #automation: !include automations.yaml
  #script: !include scripts.yaml
  #scene: !include scenes.yaml

mqtt:
  sensor:
  - state_topic: "iot/5/car"
    name: car_count

group:
  default_view:
    name: "Parking Lot"
    entities:
      - sensor.car_count

